namespace: demo

deployment:
  name: multi-container-app
  replicas: 1

containers:
  - name: frontend
    repository: nginx
    tag: latest
    containerPort: 80

  - name: backend
    repository: hashicorp/http-echo
    tag: latest
    containerPort: 5678
    args:
      - "-text=Hello from Backend"

  - name: cache
    repository: redis
    tag: latest
    containerPort: 6379

  - name: queue
    repository: rabbitmq
    tag: latest
    containerPort: 5672
