namespace: demo

deployment:
  strategy: RollingUpdate

images:
  - name: frontend
    repository: nginx
    tag: latest
    replicas: 1
    containerPort: 80
    service:
      enabled: true
      port: 80

  - name: backend
    repository: hashicorp/http-echo
    tag: latest
    replicas: 1
    containerPort: 5678
    service:
      enabled: true
      port: 5678

  - name: cache
    repository: redis
    tag: latest
    replicas: 1
    containerPort: 6379
    service:
      enabled: true
      port: 6379

  - name: queue
    repository: rabbitmq
    tag: latest
    replicas: 1
    containerPort: 5672
    service:
      enabled: true
      port: 5672
