namespace: demo
deployment:
  strategy: RollingUpdate
images:
- name: service-a
  repository: nginx
  tag: latest
  replicas: 2
  containerPort: 80
  service: {enabled: true, port: 80}
- name: service-b
  repository: redis
  tag: latest
  replicas: 1
  containerPort: 6379
  service: {enabled: true, port: 6379}
- name: service-c
  repository: httpd
  tag: latest
  replicas: 2
  containerPort: 80
  service: {enabled: true, port: 80}
