apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}

    spec:
      containers:
{{- range .Values.containers }}
        - name: {{ .name }}
          image: "{{ .repository }}:{{ .tag }}"
{{- if .args }}
          args:
{{ toYaml .args | indent 12 }}
{{- end }}
          ports:
            - containerPort: {{ .containerPort }}
{{- end }}
